version: "3.7"

services:

  user:
    build:
      dockerfile: Dockerfileuser
    container_name: user
    restart: always
    environment: 
      - APP_NAME=user

  app:
    build:
      dockerfile: Dockerfileapp
    container_name: app
    restart: always
    environment: 
       - APP_NAME=app
  
  
  nginx:
    build: ./nginx
    container_name: nginx 
    restart: always
    ports:
     - "80:80"
