version: "3.7"

services:

# Build docker container: user
  user:
    build:
      dockerfile: Dockerfileuser
    container_name: user
    restart: always
    environment: 
      - APP_NAME=user

# Build docker container: app
  app:
    build:
      dockerfile: Dockerfileapp
    container_name: app
    restart: always
    environment: 
       - APP_NAME=app
  
# Build docker container nginx using the settings in ./nginx
  nginx:
    build: ./nginx
    container_name: nginx 
    restart: always
    ports:
     - "80:80"
