#Kubernets API version
apiVersion: apps/v1
# Kubernets Resource Type: Deployment
kind: Deployment
metadata:
  # Deployment Name: user-deployment
  name: user-deployment
  # key-value set
  labels:
    app: user
spec:
  # Create 3 replicas (Pods)
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      # Get image from the container k8s-user
      containers:
          #contianer name
        - name: k8s-user
          #image name
          image: k8s-user
          #image pull policy, the docker image is already build in the local
          imagePullPolicy: Never
          #docker container port
          ports:
            # port for shortener app: 5001
            - containerPort: 5001
