#Kubernets API version
apiVersion: apps/v1
# Kubernets Resource Type: Deployment
kind: Deployment
metadata:
  # Deployment Name: app-deployment
  name: app-deployment
  # key-value set
  labels:
    app: app
spec:
  # Create 3 replicas (Pods)
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      # Get image from the container k8s-app
      containers:
          #contianer name
        - name: k8s-app
          #image name
          image: k8s-app
          #image pull policy, the docker image is already build in the local
          imagePullPolicy: Never 
          #docker container port
          ports:
            # port for shortener app: 5002
            - containerPort: 5002
