#Kubernets API version
apiVersion: v1
# Kubernets Resource Type: Service
kind: Service
metadata:
  # Service Name: app-service
  name: user-service
  # key-value set
  labels:
    app: user
spec:
  ports:
    - port: 5001
      nodePort: 30007
      targetPort: 5001
  selector:
    app: user
  type: NodePort
