#Kubernets API version
apiVersion: v1
# Kubernets Resource Type: Service
kind: Service
metadata:
  # Service Name: app-service
  name: app-service
spec:
  ports:
  - port: 5002
    nodePort: 30008
    targetPort: 5002
  selector:
    app: app
  type: NodePort
